[package]
name = "mangatan_android"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
autobins = false 

[package.metadata.android]
package = "com.mangatan.app"
label = "Mangatan"
min_sdk_version = 23
target_sdk_version = 28 
build_targets = ["aarch64-linux-android"]
assets = "assets"

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[[package.metadata.android.uses_permission]]
name = "android.permission.ACCESS_NETWORK_STATE"

[package.metadata.android.application]
allow_native_heap_pointer_tagging = false
request_legacy_external_storage = true

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
android-activity = { version = "0.6", features = ["native-activity"] }
axum.workspace = true
eframe = { version = "0.33", default-features = false, features = ["wgpu", "android-native-activity" ] }
egui = "0.33"
futures.workspace = true
jni.workspace = true
lazy_static.workspace = true
libc.workspace = true
libloading.workspace = true
mangatan-ocr-server.workspace = true
mime_guess.workspace = true
openssl.workspace = true
reqwest.workspace = true
tar.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
winit = "0.30"
